server:
  port: 8082
  host: "0.0.0.0"
  read_timeout: 30s
  write_timeout: 30s
  shutdown_timeout: 10s

elasticsearch:
  urls:
    - "http://localhost:9200"
  username: ""
  password: ""
  api_key: ""
  tls:
    insecure_skip_verify: false

logging:
  level: "info"
  format: "json"
  output: "stdout"